# Generated by Django 4.1.7 on 2023-05-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=30, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Table_1',
            },
        ),
    ]
