# Generated by Django 4.1.7 on 2023-06-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_calc_cloud_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud_2',
            fields=[
                ('Email', models.EmailField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField()),
                ('Password', models.CharField(max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Table_2',
            },
        ),
    ]
