# Generated by Django 4.1.7 on 2023-07-04 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cloud_22'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction_add_timing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Time', models.TimeField(auto_now_add=True)),
                ('Amount', models.IntegerField()),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cloud_2')),
            ],
            options={
                'db_table': 'Transaction_details',
            },
        ),
    ]
