# Generated by Django 4.1.7 on 2023-07-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_transaction_add_timing'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction_add_timing',
            table='Add_money_history',
        ),
    ]
