# Generated by Django 4.1.7 on 2023-07-05 06:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_transaction_add_timing_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_number', models.IntegerField()),
                ('Expiry', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Expiry date must be in the format of "MM/YY"', regex='^\\d{2}/\\d{2}$')])),
                ('CVV', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cloud_2')),
            ],
            options={
                'db_table': 'card_details',
            },
        ),
    ]
