# Generated by Django 4.1.7 on 2023-07-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Card_number',
            field=models.BigIntegerField(),
        ),
    ]
