# Generated by Django 4.1.7 on 2023-07-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_card_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_present',
            field=models.BooleanField(default=False),
        ),
    ]
